=== MatiasNAmendola/iwfms/specifications/xml/jobDescription.xsd
<?xml version="1.0" encoding="UTF-8"?><!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by Joseph (Imperial) --><xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">	<xs:element name="JobDescription">		<xs:annotation>			<xs:documentation>Comment describing your root element</xs:documentation>		</xs:annotation>		<xs:complexType>			<xs:sequence maxOccurs="unbounded">				<xs:element name="db" type="dbType"/>			</xs:sequence>		</xs:complexType>	</xs:element>	<xs:complexType name="dbTableFieldsType">		<xs:sequence maxOccurs="unbounded">			<xs:element name="dbFieldName"/>			<xs:element name="presentationName"/>		</xs:sequence>	</xs:complexType>	<xs:complexType name="dbContentsType">		<xs:sequence maxOccurs="unbounded">			<xs:element name="dbTablename"/>			<xs:element name="dbTableFields" type="dbTableFieldsType"/>		</xs:sequence>	</xs:complexType>	<xs:complexType name="dbType">		<xs:sequence maxOccurs="unbounded">			<xs:element name="dbName"/>			<xs:element name="dbContents" type="dbContentsType" maxOccurs="unbounded"/>		</xs:sequence>	</xs:complexType></xs:schema>

=== MatiasNAmendola/iwfms/specifications/xml/drugsFailure.xml
<?xml version="1.0" encoding="UTF-8"?>
<JobDescription xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Documents and Settings\Joseph\My Documents\Computing yr4\Masters Project\xml\jobDescription.xsd">
	<db>
		<dbName>hospital</dbName>
		<dbContents>
			<dbTablename>pharmacy</dbTablename>
			<dbTableFields>
				<dbFieldName>correction</dbFieldName>
				<presentationName>drug Correction</presentationName>
			</dbTableFields>
		</dbContents>
		<dbContents>
			<dbTablename>perscriptions</dbTablename>
			<dbTableFields>
				<dbFieldName>drugs</dbFieldName>
				<presentationName>Original drugs</presentationName>
			</dbTableFields>
		</dbContents>
		</db>
</JobDescription>

=== MatiasNAmendola/iwfms/specifications/xml/drugsSpec.xml
<?xml version="1.0" encoding="UTF-8"?>
<JobDescription xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Documents and Settings\Joseph\My Documents\Computing yr4\Masters Project\xml\jobDescription.xsd">
	<db>
		<dbName>hospital</dbName>
		<dbContents>
			<dbTablename>perscriptions</dbTablename>
			<dbTableFields>
				<dbFieldName>drugs</dbFieldName>
				<presentationName>drugs</presentationName>
			</dbTableFields>
		</dbContents>

		</db>
</JobDescription>

=== MatiasNAmendola/iwfms/specifications/xml/checkdrugs.xml
<?xml version="1.0" encoding="UTF-8"?>
<JobDescription xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Documents and Settings\Joseph\My Documents\Computing yr4\Masters Project\xml\jobDescription.xsd">
	<db>
		<dbName>hospital</dbName>
		<dbContents>
			<dbTablename>pharmacy</dbTablename>
			<dbTableFields>
				<dbFieldName>correction</dbFieldName>
				<presentationName>drugs</presentationName>
			</dbTableFields>
		</dbContents>
		</db>
</JobDescription>

=== MatiasNAmendola/iwfms/specifications/xml/jobSpecification.xml
<?xml version="1.0" encoding="UTF-8"?><JobDescription xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Documents and Settings\Joseph\My Documents\Computing yr4\Masters Project\xml\jobDescription.xsd">	<db>		<dbName>hospital</dbName>		<dbContents>			<dbTablename>patient</dbTablename>			<dbTableFields>				<dbFieldName>patientName</dbFieldName>				<presentationName>Patient Name</presentationName>			</dbTableFields>		</dbContents>		<dbContents>			<dbTablename>patient</dbTablename>			<dbTableFields>				<dbFieldName>age</dbFieldName>				<presentationName>Patient Age</presentationName>				<dbFieldName>ward</dbFieldName>				<presentationName>Ward</presentationName>			</dbTableFields>		</dbContents>		<dbContents>			<dbTablename>perscriptions</dbTablename>			<dbTableFields>				<dbFieldName>drugs</dbFieldName>				<presentationName>Patient drugs</presentationName>			</dbTableFields>		</dbContents>		<dbContents>			<dbTablename>pharmacy</dbTablename>			<dbTableFields>				<dbFieldName>correction</dbFieldName>				<presentationName>Correction</presentationName>			</dbTableFields>		</dbContents>		<dbContents>			<dbTablename>pharmacytimetable</dbTablename>			<dbTableFields>				<dbFieldName>pharmacyCollection</dbFieldName>				<presentationName>Drugs Ready</presentationName>			</dbTableFields>		</dbContents>		<dbContents>			<dbTablename>controlledDrugs</dbTablename>			<dbTableFields>				<dbFieldName>controlledDrugs</dbFieldName>				<presentationName>Controlled Drugs Approved</presentationName>			</dbTableFields>		</dbContents>		</db></JobDescription>

=== MatiasNAmendola/iwfms/specifications/xml/jobSpecification_backup.xml
<?xml version="1.0" encoding="UTF-8"?><JobDescription xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Documents and Settings\Joseph\My Documents\Computing yr4\Masters Project\xml\jobDescription.xsd">	<db>		<dbName>iWFMS</dbName>		<dbContents>			<dbTablename>text1</dbTablename>			<dbTableFields>				<dbFieldName>text1</dbFieldName>				<presentationName>Data Text 1</presentationName>			</dbTableFields>		</dbContents>		<dbContents>			<dbTablename>text2</dbTablename>			<dbTableFields>				<dbFieldName>text2</dbFieldName>				<presentationName>Data Text 2</presentationName>			</dbTableFields>		</dbContents>		</db></JobDescription>

=== MatiasNAmendola/iwfms/specifications/xml/succedDrugAuthorise.xml
<?xml version="1.0" encoding="UTF-8"?>
<JobDescription xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Documents and Settings\Joseph\My Documents\Computing yr4\Masters Project\xml\jobDescription.xsd">
	<db>
		<dbName>hospital</dbName>
		<dbContents>
			<dbTablename>pharmacyTimetable</dbTablename>
			<dbTableFields>
				<dbFieldName>pharmacyTimescale</dbFieldName>
				<presentationName>Time scale</presentationName>
			</dbTableFields>
		</dbContents>
		</db>
</JobDescription>

=== MatiasNAmendola/iwfms/specifications/xml/controlledDrugsSpec.xml
<?xml version="1.0" encoding="UTF-8"?>
<JobDescription xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Documents and Settings\Joseph\My Documents\Computing yr4\Masters Project\xml\jobDescription.xsd">
	<db>
		<dbName>hospital</dbName>
		<dbContents>
			<dbTablename>perscriptions</dbTablename>
			<dbTableFields>
				<dbFieldName>drugs</dbFieldName>
				<presentationName>Perscribed Drugs</presentationName>
			</dbTableFields>
		</dbContents>
		<dbContents>
			<dbTablename>pharmacy</dbTablename>
			<dbTableFields>
				<dbFieldName>correction</dbFieldName>
				<presentationName>Correction if any</presentationName>
			</dbTableFields>
		</dbContents>
		</db>
</JobDescription>
